export const Users = [
    {
        id:1,
        profilePicture:"assets/Persons/1.jpg",
        username:"John",
    },
    {
        id:2,
        profilePicture:"assets/Persons/2.jpg",
        username:"Liya",
    },
    {
        id:3,
        profilePicture:"assets/Persons/3.jpg",
        username:"Apsara",
    },
    {
        id:4,
        profilePicture:"assets/Persons/4.jpg",
        username:"Joe",
    },
    {
        id:5,
        profilePicture:"assets/Persons/5.jpg",
        username:"Peter",
    },
    {
        id:6,
        profilePicture:"assets/Persons/6.jpg",
        username:"Emma",
    },

]